#!/usr/bin/env python3
"""
Build the Cube FX simulator to WebAssembly.

    python build.py

The whole design rule here is that the simulator runs the SAME code the cube
runs, so anything it could get subtly wrong is taken from the firmware sources
rather than re-derived:

  * effects              compiled straight from usermods/cube_fx/
  * sin8_t / cos8_t      compiled from wled00/wled_math.cpp
  * scale8, qadd8, ...   compiled from fastled_slim.cpp
  * perlin noise         EXTRACTED from wled00/util.cpp at build time

That last one needs explaining. perlin8() lives in util.cpp, which drags in
Arduino, mbedtls and ESP headers and cannot be compiled on a host. But the noise
block itself is self-contained, so this script lifts exactly that block into a
generated file instead of hand-copying it. Hand-copying would work once and then
rot silently the first time upstream touched the noise - and since every
magnitude we tune (curl gain, densities, spin constants) is calibrated against
the noise field's actual shape, a stale copy would make the simulator confidently
wrong rather than obviously broken.
"""
import os, re, subprocess, sys, glob

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
EMSDK = os.environ.get("EMSDK_ENV", r"C:\Users\seang\emsdk\emsdk_env.bat")

GEN = os.path.join(HERE, "gen")
os.makedirs(GEN, exist_ok=True)


def extract_noise():
    """Lift the self-contained Perlin block out of util.cpp."""
    src = open(os.path.join(ROOT, "wled00", "util.cpp"), encoding="utf-8",
               errors="surrogateescape").read()

    # Start at the PERLIN_SHIFT define, not at gradient1D: the gradient helpers
    # lean on it and on hashToGradient(), both of which sit just above.
    start = src.find("#define PERLIN_SHIFT")
    if start < 0:
        sys.exit("build: could not find PERLIN_SHIFT in util.cpp - has the noise moved?")

    end_marker = "uint8_t perlin8(uint16_t x, uint16_t y, uint16_t z)"
    end = src.find(end_marker)
    if end < 0:
        sys.exit("build: could not find perlin8(x,y,z) in util.cpp")
    end = src.find("}", src.find("{", end)) + 1

    body = src[start:end]
    out = ('// GENERATED by build.py - do not edit.\n'
           '// Lifted verbatim from wled00/util.cpp so the simulator\'s noise is\n'
           '// bit-for-bit the noise the firmware computes.\n'
           '#include "../shim/wled.h"\n\n' + body + "\n")
    path = os.path.join(GEN, "wled_noise.cpp")
    prev = open(path, encoding="utf-8").read() if os.path.exists(path) else None
    if prev != out:
        open(path, "w", encoding="utf-8").write(out)
        print(f"  extracted noise -> gen/wled_noise.cpp ({body.count(chr(10))} lines)")
    else:
        print("  noise unchanged")
    return path


# Stock WLED effects pulled in for side-by-side comparison. Each entry is
# (start marker, end marker, exported name). They are EXTRACTED rather than
# reimplemented for the same reason the noise is: a hand-written "equivalent"
# of Soap is precisely the thing that cannot settle an argument about whether
# ours matches it.
#
# Adding another is one line - find a self-contained mode_* in FX.cpp and name
# the first symbol above it that it depends on.
STOCK = [
    ("static void soapPixels(", "static const char _data_FX_MODE_2DSOAP",   "mode_2Dsoap"),
    ("void mode_2Doctopus()",   "static const char _data_FX_MODE_2DOCTOPUS", "mode_2Doctopus"),
]


def extract_span(src, a, b, what):
    i = src.find(a)
    if i < 0:
        sys.exit(f"build: could not find start of {what} ('{a}') in FX.cpp")
    j = src.find(b, i)
    if j < 0:
        sys.exit(f"build: could not find end of {what} ('{b}') in FX.cpp")
    return src[i:j]


def extract_stock():
    """Lift ColorFromPalette and the chosen stock effects out of the firmware."""
    colors = open(os.path.join(ROOT, "wled00", "colors.cpp"), encoding="utf-8",
                  errors="surrogateescape").read()
    cfp = extract_span(colors, "uint32_t ColorFromPalette(", "void setRandomColor(",
                       "ColorFromPalette")

    fxsrc = open(os.path.join(ROOT, "wled00", "FX.cpp"), encoding="utf-8",
                 errors="surrogateescape").read()
    parts = [extract_span(fxsrc, a, b, name) for a, b, name in STOCK]

    out = ('// GENERATED by build.py - do not edit.\n'
           '// Stock WLED code, lifted verbatim so comparisons are against the real\n'
           '// thing rather than against a paraphrase of it.\n'
           '#include "../shim/wled.h"\n\n' + cfp + "\n" + "\n".join(parts) + "\n")
    path = os.path.join(GEN, "wled_fx.cpp")
    prev = open(path, encoding="utf-8").read() if os.path.exists(path) else None
    if prev != out:
        open(path, "w", encoding="utf-8").write(out)
        print(f"  extracted {len(STOCK)} stock effects + ColorFromPalette -> gen/wled_fx.cpp")
    else:
        print("  stock effects unchanged")
    return path


def main():
    print("cube_sim build")
    noise = extract_noise()
    stock = extract_stock()

    fx = sorted(glob.glob(os.path.join(ROOT, "usermods", "cube_fx", "cube_fx_[0-9][0-9]_*.cpp")))
    fx.append(os.path.join(ROOT, "usermods", "cube_fx", "cube_fx.cpp"))
    print(f"  {len(fx)} effect translation units")

    srcs = ([os.path.join(HERE, "sim_main.cpp")] + fx + [noise, stock,
            os.path.join(ROOT, "wled00", "wled_math.cpp"),
            os.path.join(ROOT, "wled00", "src", "dependencies", "fastled_slim", "fastled_slim.cpp")])

    cmd = ["emcc", "-std=gnu++17", "-O2", "-I", "shim"] + srcs + [
        "-o", "cubefx.js",
        # HEAPU8/HEAPU32 must be listed explicitly - current Emscripten does not
        # attach the heap views to the module by default, and reading pixels
        # back is the entire point of the exercise.
        "-s", "EXPORTED_RUNTIME_METHODS=ccall,cwrap,UTF8ToString,HEAPU8,HEAPU32",
        "-s", "ALLOW_MEMORY_GROWTH=1",
        "-s", "MODULARIZE=1",
        "-s", "EXPORT_NAME=CubeFX",
        "-s", "ENVIRONMENT=web",
    ]
    line = " ".join(f'"{c}"' if " " in c else c for c in cmd)
    r = subprocess.run(f'"{EMSDK}" >nul 2>&1 && {line}', shell=True, cwd=HERE,
                       capture_output=True, text=True)
    out = (r.stdout or "") + (r.stderr or "")
    if r.returncode != 0:
        print(out[:4000]); sys.exit(f"build FAILED ({r.returncode})")
    if out.strip():
        print(out[:1500])
    for f in ("cubefx.js", "cubefx.wasm"):
        p = os.path.join(HERE, f)
        print(f"  {f}: {os.path.getsize(p):,} bytes" if os.path.exists(p) else f"  {f}: MISSING")
    print("build OK")


if __name__ == "__main__":
    main()
