#!/usr/bin/env python3
"""
Build the Cube FX simulator to WebAssembly.

    python build.py

The whole design rule here is that the simulator runs the SAME code the cube
runs, so anything it could get subtly wrong is taken from the firmware sources
rather than re-derived:

  * effects              compiled straight from usermods/cube_fx/
  * sin8_t / cos8_t      compiled from wled00/wled_math.cpp
  * scale8, qadd8, ...   compiled from fastled_slim.cpp
  * perlin noise         EXTRACTED from wled00/util.cpp at build time

That last one needs explaining. perlin8() lives in util.cpp, which drags in
Arduino, mbedtls and ESP headers and cannot be compiled on a host. But the noise
block itself is self-contained, so this script lifts exactly that block into a
generated file instead of hand-copying it. Hand-copying would work once and then
rot silently the first time upstream touched the noise - and since every
magnitude we tune (curl gain, densities, spin constants) is calibrated against
the noise field's actual shape, a stale copy would make the simulator confidently
wrong rather than obviously broken.
"""
import os, re, subprocess, sys, glob

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
EMSDK = os.environ.get("EMSDK_ENV", r"C:\Users\seang\emsdk\emsdk_env.bat")

GEN = os.path.join(HERE, "gen")
os.makedirs(GEN, exist_ok=True)


def extract_noise():
    """Lift the self-contained Perlin block out of util.cpp."""
    src = open(os.path.join(ROOT, "wled00", "util.cpp"), encoding="utf-8",
               errors="surrogateescape").read()

    # Start at the PERLIN_SHIFT define, not at gradient1D: the gradient helpers
    # lean on it and on hashToGradient(), both of which sit just above.
    start = src.find("#define PERLIN_SHIFT")
    if start < 0:
        sys.exit("build: could not find PERLIN_SHIFT in util.cpp - has the noise moved?")

    end_marker = "uint8_t perlin8(uint16_t x, uint16_t y, uint16_t z)"
    end = src.find(end_marker)
    if end < 0:
        sys.exit("build: could not find perlin8(x,y,z) in util.cpp")
    end = src.find("}", src.find("{", end)) + 1

    body = src[start:end]
    out = ('// GENERATED by build.py - do not edit.\n'
           '// Lifted verbatim from wled00/util.cpp so the simulator\'s noise is\n'
           '// bit-for-bit the noise the firmware computes.\n'
           '#include "../shim/wled.h"\n\n' + body + "\n")
    path = os.path.join(GEN, "wled_noise.cpp")
    prev = open(path, encoding="utf-8").read() if os.path.exists(path) else None
    if prev != out:
        open(path, "w", encoding="utf-8").write(out)
        print(f"  extracted noise -> gen/wled_noise.cpp ({body.count(chr(10))} lines)")
    else:
        print("  noise unchanged")
    return path


# Stock WLED effects pulled in for side-by-side comparison. Each entry is
# (start marker, end marker, exported name). They are EXTRACTED rather than
# reimplemented for the same reason the noise is: a hand-written "equivalent"
# of Soap is precisely the thing that cannot settle an argument about whether
# ours matches it.
#
# Adding another is one line - find a self-contained mode_* in FX.cpp and name
# the first symbol above it that it depends on.
# Every 2-D effect in FX.cpp is pulled in, discovered rather than listed. The
# previous hand-written list held two of thirty-seven, which made "compare ours
# against WLED's" a much narrower claim than it sounded.
#
# Skipped, with the reason, because a simulator that silently omits things is
# worse than one that says what it left out:
STOCK_SKIP = {
    # Needs the font manager, the RTC and sprintf. None of that says anything
    # about how an effect looks on a cube.
    "mode_2Dscrollingtext": "needs fonts, the clock and printf",
    # Depends on a `Cell` struct declared at file scope in FX.cpp, well above
    # the effect bodies. Each span here runs from one effect to the next, so
    # anything declared before the first of them is out of reach. Pulling in
    # arbitrary file-scope declarations is a much larger change than this is
    # worth for one effect.
    "mode_2Dgameoflife": "needs a file-scope type the per-effect spans cannot reach",
}


def extract_span(src, a, b, what):
    i = src.find(a)
    if i < 0:
        sys.exit(f"build: could not find start of {what} ('{a}') in FX.cpp")
    j = src.find(b, i)
    if j < 0:
        sys.exit(f"build: could not find end of {what} ('{b}') in FX.cpp")
    return src[i:j]


def balance_conditionals(text):
    """Make a span's preprocessor directives self-contained.

    The 2-D effects sit inside `#ifndef WLED_DISABLE_2D` blocks that open and
    close around GROUPS of effects, so a span cut anywhere in the middle takes
    the `#if` without its `#endif` or the other way round. Either way clang
    reports an unterminated conditional and swallows every effect after it -
    three of them vanished that way while still being registered.

    Nothing here defines any of the WLED_DISABLE_* macros, so every one of these
    blocks is active regardless. Dropping an orphaned `#endif` and closing an
    unclosed `#if` therefore changes nothing about which code is compiled.
    """
    out, depth = [], 0
    for line in text.splitlines(keepends=True):
        st = line.lstrip()
        if st.startswith("#if"):
            depth += 1
        elif st.startswith("#endif"):
            if depth == 0:
                continue                      # orphan: its opener is elsewhere
            depth -= 1
        elif st.startswith(("#else", "#elif")) and depth == 0:
            continue
        out.append(line)
    return "".join(out) + ("\n#endif\n" * depth)


def discover_stock(fxsrc):
    """Find every 2-D effect in FX.cpp and lift it with its metadata string.

    Each effect is taken as the span from its own definition to the one after
    it, which sweeps up the file-static helpers that sit between them - the
    little per-effect functions like soapPixels that the effect cannot compile
    without and that nothing else references.
    """
    fn = re.compile(r"^\s*(?:static\s+)?(?:uint16_t|void)\s+(mode_2D\w+)\s*\([^)]*\)\s*\{",
                    re.M)
    hits = [(m.start(), m.group(1)) for m in fn.finditer(fxsrc)]
    if not hits:
        sys.exit("build: found no mode_2D* effects in FX.cpp - has the file moved?")

    # Each span runs from where the PREVIOUS one ended, not from the function
    # itself, so the declarations sitting between two effects come along with
    # the effect that needs them - `typedef struct Julia` six lines above
    # mode_2DJulia, `#define MAX_BEES 5` above the bees. Starting at the
    # function left those behind and the effects would not compile.
    # Metadata strings are collected SEPARATELY from bodies and emitted first.
    #
    # An earlier version carried each effect's metadata along inside its own
    # span and tracked where the last one ended. That bookkeeping was wrong
    # whenever a declaration sat in an unexpected place: three effects were
    # registered while their bodies had been trimmed off, so the file referred
    # to functions it did not contain. Collecting the two independently means a
    # body cannot be lost by a mistake about where its metadata was.
    #
    # The string literal must be matched AS a literal. Stopping at the first
    # semicolon truncates every one of them, since WLED's metadata format is
    # full of semicolons - "Black Hole@Fade rate,...,Blur;;!;2".
    LIT = r'\[\]\s*PROGMEM\s*=\s*"(?:[^"\\]|\\.)*"\s*;'
    bodies, metas, reg, skipped = [], [], [], []
    prev_end = hits[0][0]
    for k, (pos, name) in enumerate(hits):
        # Usually the symbol is the function name upper-cased, but not always:
        # mode_2Dfloatingblobs registers _data_FX_MODE_2DBLOBS. Guess first,
        # then fall back to whichever metadata declaration sits inside this
        # effect's own span - which is the one that belongs to it.
        sym = "_data_FX_MODE_" + name[len("mode_"):].upper()
        mm = re.search(r'static const char ' + sym + LIT, fxsrc)
        if not mm:
            span_end = hits[k + 1][0] if k + 1 < len(hits) else len(fxsrc)
            near = re.search(r'static const char (_data_FX_MODE_\w+)' + LIT,
                             fxsrc[pos:span_end])
            if near:
                sym = near.group(1)
                mm = re.search(r'static const char ' + sym + LIT, fxsrc)
        # The LAST effect must stop at its own metadata, not run to the end of
        # the file. Letting it run swept in every particle-system effect that
        # follows the 2-D block, and the build then failed asking for the whole
        # ParticleSystem2D library on behalf of an effect that never used it.
        if k + 1 < len(hits):
            end = hits[k + 1][0]
        else:
            end = mm.end() if (mm and mm.start() > pos) else len(fxsrc)
        # From where the last effect finished, so declarations sitting between
        # two effects come along with the one that needs them.
        body = fxsrc[prev_end:end]
        prev_end = end
        if name in STOCK_SKIP:
            skipped.append(name)
            continue
        if not mm:
            skipped.append(name + f" (no {sym})")
            continue
        # Strip metadata out of the body; it is emitted once, up front.
        bodies.append(balance_conditionals(
            re.sub(r'static const char _data_FX_MODE_\w+' + LIT, "", body)))
        metas.append(mm.group(0))
        reg.append((name, sym))
    for s in skipped:
        print(f"  stock: skipping {s} - {STOCK_SKIP.get(s, 'could not be isolated')}")
    return ["\n".join(metas) + "\n"] + bodies, reg


def extract_stock():
    """Lift ColorFromPalette and the chosen stock effects out of the firmware."""
    colors = open(os.path.join(ROOT, "wled00", "colors.cpp"), encoding="utf-8",
                  errors="surrogateescape").read()
    cfp = extract_span(colors, "uint32_t ColorFromPalette(", "void setRandomColor(",
                       "ColorFromPalette")

    fxsrc = open(os.path.join(ROOT, "wled00", "FX.cpp"), encoding="utf-8",
                 errors="surrogateescape").read()
    parts, reg = discover_stock(fxsrc)

    # The roster is built here rather than in sim_main.cpp: the metadata strings
    # are static to this translation unit, and keeping the list beside the
    # extraction means it cannot fall out of step with what was extracted.
    reglines = "\n".join(f"  cfxBankAdd(&{fn}, {meta});" for fn, meta in reg)
    out = ('// GENERATED by build.py - do not edit.\n'
           '// Stock WLED code, lifted verbatim so comparisons are against the real\n'
           '// thing rather than against a paraphrase of it. Every 2-D effect in\n'
           '// FX.cpp is taken, discovered rather than listed.\n'
           '#include "../shim/wled.h"\n'
           '#include "../../usermods/cube_fx/cube_fx_bank.h"\n\n'
           + cfp + "\n" + "\n".join(parts) + "\n"
           "void simRegisterStock() {\n" + reglines + "\n}\n")
    path = os.path.join(GEN, "wled_fx.cpp")
    prev = open(path, encoding="utf-8").read() if os.path.exists(path) else None
    if prev != out:
        open(path, "w", encoding="utf-8").write(out)
        print(f"  extracted {len(reg)} stock 2-D effects + ColorFromPalette -> gen/wled_fx.cpp")
    else:
        print(f"  stock effects unchanged ({len(reg)})")
    return path


def find_vcvarsall():
    """Locate MSVC. vswhere is the supported way and survives version bumps."""
    pf = os.environ.get("ProgramFiles(x86)", r"C:\Program Files (x86)")
    vswhere = os.path.join(pf, "Microsoft Visual Studio", "Installer", "vswhere.exe")
    if os.path.exists(vswhere):
        r = subprocess.run([vswhere, "-latest", "-products", "*",
                            "-requires", "Microsoft.VisualStudio.Component.VC.Tools.x86.x64",
                            "-property", "installationPath"],
                           capture_output=True, text=True)
        root = (r.stdout or "").strip().splitlines()
        if root:
            p = os.path.join(root[0], "VC", "Auxiliary", "Build", "vcvarsall.bat")
            if os.path.exists(p):
                return p
    for p in glob.glob(os.path.join(pf, "Microsoft Visual Studio", "*", "*",
                                    "VC", "Auxiliary", "Build", "vcvarsall.bat")):
        return p
    return None


def build_native(srcs):
    """Compile the same sources into a DLL the native front end loads by ctypes.

    Native is the more faithful of the two targets, not the less: the same C++
    with one fewer translation layer under it. The extraction above is shared,
    so neither target can drift from the firmware sources or from each other.

    Built with the clang that ships inside emsdk, NOT with MSVC, and that choice
    is load-bearing. CFX_NET_PREP declares `uint8_t _outCol[cols]` - a
    variable-length array, a GCC/clang extension MSVC has never supported and
    rejects outright in every effect that renders. The choice was to change
    firmware to suit a host compiler, or to pick a host compiler that takes the
    firmware as written; the second is obviously right for a tool whose whole
    value is compiling the real sources unmodified. emsdk's clang already
    defaults to x86_64-pc-windows-msvc, so it emits ordinary Windows binaries
    and needs nothing installed that is not here already.

    MSVC still supplies the headers and import libraries, so vcvarsall is
    sourced for its INCLUDE/LIB - clang honours both when targeting the MSVC ABI.
    """
    vc = find_vcvarsall()
    if not vc:
        print("  native: SKIPPED - no MSVC found. clang needs its headers and "
              "import libraries; install VS Build Tools with the C++ workload.")
        return False
    clang = os.environ.get("SIM_CLANG", os.path.join(
        os.path.expanduser("~"), "emsdk", "upstream", "bin", "clang++.exe"))
    if not os.path.exists(clang):
        print(f"  native: SKIPPED - no clang++ at {clang} (set SIM_CLANG to override)")
        return False

    fs = lambda p: p.replace("\\", "/")
    out = fs(os.path.join(HERE, "cubefx.dll"))
    cmd = [f'"{fs(clang)}"', "-std=gnu++17", "-O2", "-shared",
           "-I", f'"{fs(os.path.join(HERE, "shim"))}"',
           # MSVC's headers keep M_PI and friends behind this, where the glibc
           # and Emscripten headers hand them over unconditionally. wled_math.cpp
           # uses them and quite reasonably does not ask.
           "-D_USE_MATH_DEFINES",
           # Selects the LEGACY implementations of the effects WLED otherwise
           # replaces with particle-system versions. The particle system is a
           # whole subsystem this shim has no business hosting, and the legacy
           # effects are self-contained - so the flag that keeps them is the
           # flag this build wants.
           "-DWLED_PS_DONT_REPLACE_2D_FX",
           # The roster is sized for the DEVICE, where it caps how many
           # effects can be compiled in. The simulator has no such
           # constraint, and with every WLED 2-D effect pulled in as well
           # the default 64 silently dropped the last ten - cfxBankAdd
           # returns quietly when the roster is full.
           "-DCFX_BANK_MAX_FX=128",
           "-Wno-vla-cxx-extension", "-Wno-unknown-attributes",
           "-Wno-deprecated-declarations"] + \
          [f'"{fs(s)}"' for s in srcs] + ["-o", f'"{out}"']
    line = " ".join(cmd)
    r = subprocess.run(f'"{vc}" x64 >nul && {line}', shell=True, cwd=HERE,
                       capture_output=True, text=True)
    txt = (r.stdout or "") + (r.stderr or "")
    if r.returncode != 0:
        errs = [l for l in txt.splitlines() if "error:" in l or " error " in l]
        print("\n".join(errs[:25]) or txt[:3000])
        print(f"  native: FAILED ({r.returncode})")
        return False
    print(f"  cubefx.dll: {os.path.getsize(out):,} bytes")
    return True


def main():
    want = set(sys.argv[1:]) or {"--wasm", "--native"}
    if "--wasm-only" in want:   want = {"--wasm"}
    if "--native-only" in want: want = {"--native"}

    print("cube_sim build")
    noise = extract_noise()
    stock = extract_stock()

    fx = sorted(glob.glob(os.path.join(ROOT, "usermods", "cube_fx", "cube_fx_[0-9][0-9]_*.cpp")))
    fx.append(os.path.join(ROOT, "usermods", "cube_fx", "cube_fx.cpp"))
    print(f"  {len(fx)} effect translation units")

    srcs = ([os.path.join(HERE, "sim_main.cpp")] + fx + [noise, stock,
            os.path.join(ROOT, "wled00", "wled_math.cpp"),
            os.path.join(ROOT, "wled00", "src", "dependencies", "fastled_slim", "fastled_slim.cpp")])

    if "--native" in want:
        build_native(srcs)
    if "--wasm" not in want:
        print("build OK")
        return

    cmd = ["emcc", "-std=gnu++17", "-O2", "-I", "shim",
           "-DWLED_PS_DONT_REPLACE_2D_FX", "-DCFX_BANK_MAX_FX=128"] + srcs + [
        "-o", "cubefx.js",
        # HEAPU8/HEAPU32 must be listed explicitly - current Emscripten does not
        # attach the heap views to the module by default, and reading pixels
        # back is the entire point of the exercise.
        "-s", "EXPORTED_RUNTIME_METHODS=ccall,cwrap,UTF8ToString,HEAPU8,HEAPU32",
        "-s", "ALLOW_MEMORY_GROWTH=1",
        "-s", "MODULARIZE=1",
        "-s", "EXPORT_NAME=CubeFX",
        "-s", "ENVIRONMENT=web",
    ]
    line = " ".join(f'"{c}"' if " " in c else c for c in cmd)
    r = subprocess.run(f'"{EMSDK}" >nul 2>&1 && {line}', shell=True, cwd=HERE,
                       capture_output=True, text=True)
    out = (r.stdout or "") + (r.stderr or "")
    if r.returncode != 0:
        print(out[:4000]); sys.exit(f"build FAILED ({r.returncode})")
    if out.strip():
        print(out[:1500])
    for f in ("cubefx.js", "cubefx.wasm"):
        p = os.path.join(HERE, f)
        print(f"  {f}: {os.path.getsize(p):,} bytes" if os.path.exists(p) else f"  {f}: MISSING")
    print("build OK")


if __name__ == "__main__":
    main()
