#include "wled.h"
#include "cube_fx_common.h"
#include "cube_fx_bank.h"

// ===========================================================================
// Gyro Sand - generated by the WLED Effect Studio node editor
// ===========================================================================
// An ordinary effect: drop it into a usermod folder that has cube_fx_common.h
// and cube_fx_bank.h beside it and it compiles into the firmware unchanged.
// Edit the graph and regenerate, or edit this file by hand from here on.
// ===========================================================================

static inline float gc_sat(float x) { return x < 0.0f ? 0.0f : (x > 1.0f ? 1.0f : x); }
static inline float gc_fract(float x) { return x - floorf(x); }
// A vector: three floats on one wire.
struct GcVec { float x, y, z; };
static inline GcVec gc_v3(float x, float y, float z) { GcVec v; v.x = x; v.y = y; v.z = z; return v; }
static inline GcVec gc_vadd(GcVec a, GcVec b) { return gc_v3(a.x + b.x, a.y + b.y, a.z + b.z); }
static inline GcVec gc_vsub(GcVec a, GcVec b) { return gc_v3(a.x - b.x, a.y - b.y, a.z - b.z); }
static inline GcVec gc_vmul(GcVec a, GcVec b) { return gc_v3(a.x * b.x, a.y * b.y, a.z * b.z); }
static inline GcVec gc_vscale(GcVec a, float s) { return gc_v3(a.x * s, a.y * s, a.z * s); }
static inline float gc_vdot(GcVec a, GcVec b) { return a.x * b.x + a.y * b.y + a.z * b.z; }
static inline float gc_vlen(GcVec a) { return sqrtf(gc_vdot(a, a)); }
static inline GcVec gc_vnorm(GcVec a) { const float L = gc_vlen(a); return L > 1e-6f ? gc_vscale(a, 1.0f / L) : gc_v3(0.0f, 0.0f, 1.0f); }
static inline GcVec gc_vcross(GcVec a, GcVec b) { return gc_v3(a.y * b.z - a.z * b.y, a.z * b.x - a.x * b.z, a.x * b.y - a.y * b.x); }
static inline GcVec gc_col2v(uint32_t c) { return gc_v3(((c >> 16) & 255) * (1.0f / 255.0f), ((c >> 8) & 255) * (1.0f / 255.0f), (c & 255) * (1.0f / 255.0f)); }
static inline uint32_t gc_v2col(GcVec v) { return RGBW32((uint8_t)(gc_sat(v.x) * 255.0f), (uint8_t)(gc_sat(v.y) * 255.0f), (uint8_t)(gc_sat(v.z) * 255.0f), 0); }
// Rotate v about a unit axis by an angle (Rodrigues).
static inline GcVec gc_vrot(GcVec v, GcVec axis, float rad) {
  const GcVec k = gc_vnorm(axis); const float c = cosf(rad), s = sinf(rad);
  return gc_vadd(gc_vadd(gc_vscale(v, c), gc_vscale(gc_vcross(k, v), s)), gc_vscale(k, gc_vdot(k, v) * (1.0f - c)));
}
static inline float gc_rnd() { return (float)hw_random16() * (1.0f / 65535.0f); }
// A stable 0..1 from a position and a seed - the same every frame for the same
// inputs, so cells, tiles and columns can each own a random number.
static inline float gc_hash(float x, float y, float seed) {
  uint32_t h = (uint32_t)(int32_t)floorf(x * 4096.0f) * 374761393u
             ^ (uint32_t)(int32_t)floorf(y * 4096.0f) * 668265263u
             ^ (uint32_t)(int32_t)floorf(seed * 4096.0f) * 2246822519u;
  h ^= h >> 13; h *= 1274126177u; h ^= h >> 16;
  return (float)(h & 0xFFFFFFu) * (1.0f / 16777215.0f);
}
// Last frame's colour at a logical position (0..1, 0..1). On a matrix that is
// a neighbour read for trails and flows; the pixels already written this
// frame read as this frame's, as WLED's own fire effects accept.
// The inverse of the lid-and-walls ruler: (around, depth) back to the logical
// pixel, as u, v - the exact inverse of cfx_pos, so a read there lands on the
// pixel Cube ring would call that. Lets a feedback read step along the ring.
static inline int gc_q(float t, int B) { int i = (int)floorf((t + 1.0f) * 0.5f * (float)B); return i < 0 ? 0 : (i > B - 1 ? B - 1 : i); }
static inline void gc_ring_uv(float around, float depth, int W, int H, int B, bool cube, float &u, float &v) {
  around -= floorf(around);
  if (!cube) { u = around; v = gc_sat(depth); return; }
  const float a = (around - 0.5f) * 6.2831853f;
  float cx_ = cosf(a), sy_ = sinf(a);
  const float m = fmaxf(fabsf(cx_), fabsf(sy_)); if (m > 1e-6f) { cx_ /= m; sy_ /= m; }
  int px_, py_;
  if (depth < 0.5f) { const float r = depth * 2.0f; px_ = B + gc_q(cx_ * r, B); py_ = B + gc_q(-sy_ * r, B); }
  else {
    const float Z = 1.0f - (depth - 0.5f) * 4.0f;
    if (fabsf(sy_) >= fabsf(cx_)) { px_ = B + gc_q(cx_, B); py_ = (sy_ > 0) ? gc_q(Z, B) : 2 * B + gc_q(-Z, B); }
    else                          { py_ = B + gc_q(-sy_, B); px_ = (cx_ < 0) ? gc_q(Z, B) : 2 * B + gc_q(-Z, B); }
  }
  u = (W > 1) ? (float)px_ / (float)(W - 1) : 0.5f; v = (H > 1) ? (float)py_ / (float)(H - 1) : 0.5f;
}
// A finite reflection group's mirrors, each normal pointed at one generic
// direction so every set is the positive roots of a single chamber and the
// fold terminates (see cube_fx_39_kaleidoscope.cpp for the reasoning).
//   sym 0..7  dihedral D(n), n = sym + 3 (with the equator)
//   sym 8     tetrahedral   sym 9  octahedral   sym 10  icosahedral
static int gc_mirrors(int sym, float m[16][3]) {
  int n = 0;
  const float gx = 0.2374f, gy = 0.4451f, gz = 0.8632f;
  #define GC_MIR(a, b, c) { if (n < 16) { m[n][0] = (a); m[n][1] = (b); m[n][2] = (c); n++; } }
  if (sym <= 7) {
    const int k = sym + 3;
    for (int i = 0; i < k; i++) { const float a = (float)i * 3.14159265f / (float)k; GC_MIR(-sinf(a), cosf(a), 0.0f); }
    GC_MIR(0.0f, 0.0f, 1.0f);
  } else if (sym <= 9) {
    if (sym == 9) { GC_MIR(1, 0, 0); GC_MIR(0, 1, 0); GC_MIR(0, 0, 1); }
    GC_MIR(1, -1, 0); GC_MIR(1, 1, 0); GC_MIR(0, 1, -1); GC_MIR(0, 1, 1); GC_MIR(1, 0, -1); GC_MIR(1, 0, 1);
  } else {
    const float P = 1.61803399f, Q = 0.61803399f;
    GC_MIR(1, 0, 0); GC_MIR(0, 1, 0); GC_MIR(0, 0, 1);
    for (int a = 0; a < 2; a++) for (int b = 0; b < 2; b++) {
      const float sa = a ? -1.0f : 1.0f, sb = b ? -1.0f : 1.0f;
      GC_MIR(1.0f, sa * P, sb * Q); GC_MIR(sa * P, sb * Q, 1.0f); GC_MIR(sb * Q, 1.0f, sa * P);
    }
  }
  #undef GC_MIR
  for (int j = 0; j < n; j++) {
    const float L = sqrtf(m[j][0] * m[j][0] + m[j][1] * m[j][1] + m[j][2] * m[j][2]);
    float sgn = (m[j][0] * gx + m[j][1] * gy + m[j][2] * gz) < 0.0f ? -1.0f : 1.0f;
    if (L > 0.0f) sgn /= L;
    m[j][0] *= sgn; m[j][1] *= sgn; m[j][2] *= sgn;
  }
  return n;
}
// Reflect a direction into the group's fundamental domain: bounce off any
// mirror it is behind until nothing moves. Two or three sweeps in practice.
static inline void gc_fold(int sym, float &x, float &y, float &z) {
  static float mir[16][3]; static int nm = 0, have = -1;
  if (have != sym) { nm = gc_mirrors(sym, mir); have = sym; }
  for (int pass = 0; pass < 4; pass++) {
    bool moved = false;
    for (int j = 0; j < nm; j++) {
      const float d = x * mir[j][0] + y * mir[j][1] + z * mir[j][2];
      if (d < 0.0f) { const float t = 2.0f * d; x -= t * mir[j][0]; y -= t * mir[j][1]; z -= t * mir[j][2]; moved = true; }
    }
    if (!moved) break;
  }
}
// Escape time of z -> z^2 + c, smoothed, as 0..1 (1 = never escaped); a
// Julia set when jx, jy are given instead of the point itself.
static inline float gc_mandel(float cx, float cy, float zx, float zy, int maxit) {
  int i = 0; float x2 = zx * zx, y2 = zy * zy;
  while (i < maxit && x2 + y2 < 16.0f) { zy = 2.0f * zx * zy + cy; zx = x2 - y2 + cx; x2 = zx * zx; y2 = zy * zy; i++; }
  if (i >= maxit) return 1.0f;
  const float nu = (float)i + 1.0f - logf(logf(sqrtf(x2 + y2)) / 0.6931472f) / 0.6931472f;
  return gc_sat(nu / (float)maxit);
}
// Any point in the -1..1 box back to the logical pixel that shows it: the
// point is pushed onto the cube's surface (the box's own max-norm) and the
// face mapping of cfx_pos is run backwards. A read one step along gravity,
// or along any 3-D direction, is this and then Field or Previous at.
static inline void gc_pos_uv(float X, float Y, float Z, int W, int H, int B, bool cube, float &u, float &v) {
  if (!cube) { u = gc_sat((X + 1.0f) * 0.5f); v = gc_sat((1.0f - Y) * 0.5f); return; }
  const float m = fmaxf(fabsf(X), fmaxf(fabsf(Y), fabsf(Z)));
  if (m > 1e-6f) { X /= m; Y /= m; Z /= m; }
  int px_, py_;
  const float ax = fabsf(X), ay = fabsf(Y), az = fabsf(Z);
  if (az >= ax && az >= ay) {                                   // top (or the missing bottom)
    px_ = B + gc_q(X, B); py_ = B + gc_q(-Y, B);
  } else if (ay >= ax) {
    px_ = B + gc_q(X, B); py_ = (Y > 0) ? gc_q(Z, B) : 2 * B + gc_q(-Z, B);
  } else {
    py_ = B + gc_q(-Y, B); px_ = (X < 0) ? gc_q(Z, B) : 2 * B + gc_q(-Z, B);
  }
  u = (W > 1) ? (float)px_ / (float)(W - 1) : 0.5f; v = (H > 1) ? (float)py_ / (float)(H - 1) : 0.5f;
}
// A (P, Q) torus knot seen from the centre: does the ray along direction n
// hit the knot's tube, and where. For azimuth u the knot passes P times, at
// t = (u + 2 pi k) / P; each pass is a point in the half-plane of u, and the
// ray hits its tube if it passes within `tube` of it. The nearest hit wins.
static inline bool gc_knot(float nx, float ny, float nz, int P, int Q, float R, float r, float tube,
                           float &along, float &edge, float &Nx, float &Ny, float &Nz) {
  const float sxy = sqrtf(nx * nx + ny * ny);
  const float u = cfx_atan2f(ny, nx);
  float bestL = 1e9f, bestT = 0.0f, bestRho = 0.0f, bestZ = 0.0f, bestD2 = 0.0f;
  const float tube2 = tube * tube;
  for (int k = 0; k < P; k++) {
    const float t = (u + 6.2831853f * (float)k) / (float)P;
    const float v = (float)Q * t;
    const float rho = R + r * cosf(v), zz = r * sinf(v);
    const float ell = rho * sxy + zz * nz;
    if (ell <= 0.0f) continue;
    float d2 = rho * rho + zz * zz - ell * ell; if (d2 < 0.0f) d2 = 0.0f;
    if (d2 < tube2) {
      const float hit = ell - sqrtf(tube2 - d2);
      if (hit > 0.0f && hit < bestL) { bestL = hit; bestT = t; bestRho = rho; bestZ = zz; bestD2 = d2; }
    }
  }
  if (bestL > 1e8f) { along = 0.0f; edge = 1.0f; Nx = Ny = 0.0f; Nz = 1.0f; return false; }
  const float qx = bestL * nx, qy = bestL * ny, qz = bestL * nz;
  const float cu = (sxy > 1e-6f) ? (nx / sxy) : 1.0f, su = (sxy > 1e-6f) ? (ny / sxy) : 0.0f;
  Nx = qx - bestRho * cu; Ny = qy - bestRho * su; Nz = qz - bestZ;
  const float NL = sqrtf(Nx * Nx + Ny * Ny + Nz * Nz); const float iN = (NL > 1e-6f) ? 1.0f / NL : 1.0f;
  Nx *= iN; Ny *= iN; Nz *= iN;
  along = bestT * (1.0f / 6.2831853f); along -= floorf(along);
  edge = sqrtf(bestD2) / tube;
  return true;
}
#if __has_include("cube_fx_imu.h")
  #include "cube_fx_imu.h"
  #define GC_HAS_IMU 1
#endif
// Gray-Scott reaction-diffusion on a small grid, periodic in x (a tunnel's
// azimuth), clamped in y. U and V interleaved; one Euler step per call.
static inline void gc_gray_scott(float *G, int gw, int gh, float Du, float Dv, float F, float k, float *tmp) {
  for (int y = 0; y < gh; y++) for (int x = 0; x < gw; x++) {
    const int i = (y * gw + x) * 2;
    const int xl = (x + gw - 1) % gw, xr = (x + 1) % gw, yu = y > 0 ? y - 1 : y, yd = y < gh - 1 ? y + 1 : y;
    const float u = G[i], v = G[i + 1];
    const float lu = G[(y * gw + xl) * 2] + G[(y * gw + xr) * 2] + G[(yu * gw + x) * 2] + G[(yd * gw + x) * 2] - 4.0f * u;
    const float lv = G[(y * gw + xl) * 2 + 1] + G[(y * gw + xr) * 2 + 1] + G[(yu * gw + x) * 2 + 1] + G[(yd * gw + x) * 2 + 1] - 4.0f * v;
    const float uvv = u * v * v;
    tmp[i]     = u + Du * lu - uvv + F * (1.0f - u);
    tmp[i + 1] = v + Dv * lv + uvv - (F + k) * v;
  }
  for (int i = 0; i < gw * gh * 2; i++) G[i] = tmp[i] < 0.0f ? 0.0f : (tmp[i] > 1.0f ? 1.0f : tmp[i]);
}
// One row of a text bitmap: rows separated by '/', '.' transparent, a digit
// its colour slot. Returns the slot at (u, v) or -1.
static inline int gc_bitmap(const char *bm, float u, float v) {
  int rows = 1; for (const char *p = bm; *p; p++) if (*p == '/') rows++;
  int r = (int)floorf(gc_sat(v) * (float)rows); if (r >= rows) r = rows - 1;
  const char *p = bm; for (int i = 0; i < r; i++) { while (*p && *p != '/') p++; if (*p) p++; }
  int cols = 0; for (const char *q = p; *q && *q != '/'; q++) cols++;
  if (cols == 0) return -1;
  int c = (int)floorf(gc_sat(u) * (float)cols); if (c >= cols) c = cols - 1;
  const char ch = p[c];
  return (ch >= '0' && ch <= '9') ? (ch - '0') : -1;
}
static inline uint32_t gc_prev_at(float u, float v, int W, int H, bool is2d) {
  int x = (int)floorf(gc_sat(u) * (float)(W - 1) + 0.5f), y = (int)floorf(gc_sat(v) * (float)(H - 1) + 0.5f);
  return is2d ? SEGMENT.getPixelColorXY(x, y) : SEGMENT.getPixelColor(x);
}
// The palette-source colour lives in the cube_fx palettes usermod. Weak, so a
// build without that usermod still links and the node falls back to the
// segment's own palette.
uint32_t cfxPaletteSourceColor(uint8_t pos, uint8_t bri) __attribute__((weak));
static inline uint32_t gc_srcpal(uint8_t pos, uint8_t bri) {
  if (cfxPaletteSourceColor) return cfxPaletteSourceColor(pos, bri);
  return mq_scale(SEGMENT.color_from_palette(pos, false, true, 0), bri);
}
static inline uint32_t gc_hsv(float h, float s, float v) {
  h -= floorf(h); const float hh = h * 6.0f; const int i = (int)hh; const float f = hh - i;
  const float p = v * (1.0f - s), q = v * (1.0f - s * f), t = v * (1.0f - s * (1.0f - f));
  float r, g, b;
  switch (i) { case 0: r=v;g=t;b=p; break; case 1: r=q;g=v;b=p; break; case 2: r=p;g=v;b=t; break;
               case 3: r=p;g=q;b=v; break; case 4: r=t;g=p;b=v; break; default: r=v;g=p;b=q; break; }
  return RGBW32((uint8_t)(gc_sat(r)*255.0f), (uint8_t)(gc_sat(g)*255.0f), (uint8_t)(gc_sat(b)*255.0f), 0);
}
static inline uint32_t gc_blend_over(uint32_t u, uint32_t o, float a)     { return color_blend(u, o, (uint8_t)(a * 255.0f)); }
static inline uint32_t gc_blend_add(uint32_t u, uint32_t o, float a)      { return color_add(u, mq_scale(o, (uint8_t)(a * 255.0f)), true); }
static inline uint32_t gc_blend_max(uint32_t u, uint32_t o, float a) {
  o = mq_scale(o, (uint8_t)(a * 255.0f)); uint32_t r = 0;
  for (int s = 0; s < 24; s += 8) { const uint32_t x = (u >> s) & 255, y = (o >> s) & 255; r |= (x > y ? x : y) << s; }
  return r; }
static inline uint32_t gc_blend_min(uint32_t u, uint32_t o, float a) {
  uint32_t r = 0;
  for (int s = 0; s < 24; s += 8) { const uint32_t x = (u >> s) & 255, y = (o >> s) & 255; const uint32_t m = x < y ? x : y;
    r |= (uint32_t)(x + (int)((int)m - (int)x) * a) << s; }
  return r; }
static inline uint32_t gc_blend_multiply(uint32_t u, uint32_t o, float a) {
  uint32_t r = 0;
  for (int s = 0; s < 24; s += 8) { const uint32_t x = (u >> s) & 255, y = (o >> s) & 255; const uint32_t m = (x * y) / 255u;
    r |= (uint32_t)(x + (int)((int)m - (int)x) * a) << s; }
  return r; }
static inline uint32_t gc_blend_screen(uint32_t u, uint32_t o, float a) {
  uint32_t r = 0;
  for (int s = 0; s < 24; s += 8) { const uint32_t x = (u >> s) & 255, y = (o >> s) & 255; const uint32_t m = 255u - ((255u - x) * (255u - y)) / 255u;
    r |= (uint32_t)(x + (int)((int)m - (int)x) * a) << s; }
  return r; }

static FX_RET mode_gyro_sand() {
  if (!strip.isMatrix && !SEGMENT.is2D() && SEGLEN < 1) { FX_DONE; }
  const bool is2d = SEGMENT.is2D();
  const int W = is2d ? SEG_W : SEGLEN, H = is2d ? SEG_H : 1;
  const int N = W * H;
  const bool cube = is2d && cfx_isCube(W, H);
  const int  B    = cube ? (W / 3) : 1;
  static uint8_t clk_[2] = {0, 0};
  const uint16_t dt = fx_dt8(clk_);
  const float t = (float)strip.now * 0.001f;
  (void)N; (void)dt; (void)t;
  // --- state kept between frames: 1 floats, 1 field(s) of N ------
  const bool gc_first = (SEGENV.call == 0);
  float *gc_st = nullptr;
  if (SEGENV.allocateData((1 + 2 * 1 * N) * sizeof(float))) gc_st = (float *)SEGENV.data;
  if (!gc_st) { SEGMENT.fill(0); FX_DONE; }   // no room for the fields
  float *gc_fr0 = gc_st + 1 + (2 * 0 + (SEGENV.call & 1)) * N;
  float *gc_fw0 = gc_st + 1 + (2 * 0 + ((SEGENV.call + 1) & 1)) * N;
  if (gc_first) memset(gc_fr0, 0, N * sizeof(float));
  (void)gc_first;

  // --- frame scope -----------------------------------------------------------
      // Speed #1
      float n1_value = 0; 
      n1_value = SEGMENT.speed * (1.0f / 255.0f);
      // Intensity #2
      float n2_value = 0; 
      n2_value = SEGMENT.intensity * (1.0f / 255.0f);
      // Custom 1 #3
      float n3_value = 0; 
      n3_value = SEGMENT.custom1 * (1.0f / 255.0f);
      // Custom 2 #4
      float n4_value = 0; 
      n4_value = SEGMENT.custom2 * (1.0f / 255.0f);
      // Check 1 #5
      bool n5_on = false; 
      n5_on = SEGMENT.check1;
      // Audio #6
      float n6_volume = 0; float n6_bass = 0; float n6_mid = 0; float n6_treble = 0; bool n6_beat = false; float n6_hit = 0; 
      { um_data_t *um = cfx_getAudioData();
        int b_, m_, t_; cfx_bands((const uint8_t *)um->u_data[2], b_, m_, t_);
        n6_volume = *(float *)um->u_data[0] * (1.0f / 255.0f);
        n6_bass = b_ * (1.0f / 255.0f); n6_mid = m_ * (1.0f / 255.0f); n6_treble = t_ * (1.0f / 255.0f);
        const uint8_t k_ = fx_lowBeat(um);
        n6_beat = k_ != 0; n6_hit = k_ * (1.0f / 255.0f); }
      // Time #7
      float n7_t = 0; float n7_dt = 0; 
      n7_t = t; n7_dt = (float)dt;
      // Remap #11
      float n11_result = 0; 
      n11_result = -0.8f + (n3_value - 0.0f) * ((0.8f - -0.8f) / ((1.0f - 0.0f) != 0.0f ? (1.0f - 0.0f) : 1.0f));
      // Remap #12
      float n12_result = 0; 
      n12_result = -0.8f + (n4_value - 0.0f) * ((0.8f - -0.8f) / ((1.0f - 0.0f) != 0.0f ? (1.0f - 0.0f) : 1.0f));
      // Gravity #13
      GcVec n13_g = GcVec{0.0f, 0.0f, 0.0f}; float n13_gx = 0; float n13_gy = 0; float n13_gz = 0; bool n13_sensor = false; 
      { float gx_ = n11_result, gy_ = n12_result, gz_ = -1.0f; n13_sensor = false;
      #ifdef GC_HAS_IMU
        { const CfxImuState &imu_ = cfx_imu(); if (imu_.valid) { gx_ = imu_.gx * (1.0f / 127.0f); gy_ = imu_.gy * (1.0f / 127.0f); gz_ = imu_.gz * (1.0f / 127.0f); n13_sensor = true; } }
      #endif
        const float L_ = sqrtf(gx_ * gx_ + gy_ * gy_ + gz_ * gz_); const float iL_ = L_ > 1e-6f ? 1.0f / L_ : 1.0f;
        n13_gx = gx_ * iL_; n13_gy = gy_ * iL_; n13_gz = gz_ * iL_; n13_g = gc_v3(n13_gx, n13_gy, n13_gz); }
      // Divide #22
      float n22_result = 0; 
      n22_result = (fabsf(16.0f) > 1e-6f) ? 2.6f / 16.0f : 0.0f;
      // Remap #93
      float n93_result = 0; 
      n93_result = 0.0f + (n1_value - 0.0f) * ((0.35f - 0.0f) / ((1.0f - 0.0f) != 0.0f ? (1.0f - 0.0f) : 1.0f));
      // Envelope #94
      float n94_value = 0; 
      if (gc_first) gc_st[0] = n6_hit;
      { const float tau_ = (n6_hit > gc_st[0]) ? 5.0f : 200.0f;
        const float k_ = tau_ > 0.0f ? 1.0f - expf(-(float)dt / tau_) : 1.0f;
        gc_st[0] += (n6_hit - gc_st[0]) * k_; }
      n94_value = gc_st[0];
      // Select #95
      float n95_result = 0; 
      n95_result = n5_on ? n94_value : 0.0f;
      // Add #96
      float n96_result = 0; 
      n96_result = n93_result + n95_result;
      // Remap #108
      float n108_result = 0; 
      n108_result = 0.3f + (n2_value - 0.0f) * ((1.0f - 0.3f) / ((1.0f - 0.0f) != 0.0f ? (1.0f - 0.0f) : 1.0f));

  // --- per pixel ---------------------------------------------------------------
  const int cols = W, rows = H; (void)rows;          // the net-skip macros' names
  CFX_NET_PREP();
  for (int py = 0; py < H; py++) {
    CFX_NET_ROW(py);
    for (int px = 0; px < W; px++) {
      CFX_NET_SKIP(px);
      const float u = (W > 1) ? (float)px / (float)(W - 1) : 0.5f;
      const float v = (H > 1) ? (float)py / (float)(H - 1) : 0.5f;
      const float cx = u * 2.0f - 1.0f, cy = 1.0f - v * 2.0f;
      const float r = sqrtf(cx * cx + cy * cy);
      const float ang = cfx_atan2f(cy, cx);
      float nx, ny, nz, X3, Y3, Z3;                 // direction (unit) and position (-1..1 box)
      if (cube) {
        cfx_pos(px, py, W, H, B, true, X3, Y3, Z3);
        const float L = sqrtf(X3 * X3 + Y3 * Y3 + Z3 * Z3); const float iL = L > 1e-6f ? 1.0f / L : 1.0f;
        nx = X3 * iL; ny = Y3 * iL; nz = Z3 * iL;
      } else {
        X3 = cx; Y3 = cy; Z3 = 0.0f;
        const float Z = 1.0f - (cx * cx + cy * cy) * 0.5f;
        const float L = sqrtf(cx * cx + cy * cy + Z * Z); const float iL = L > 1e-6f ? 1.0f / L : 1.0f;
        nx = cx * iL; ny = cy * iL; nz = Z * iL;
      }
      (void)u; (void)v; (void)r; (void)ang; (void)nx; (void)ny; (void)nz; (void)X3; (void)Y3; (void)Z3;
      uint32_t gc_out = 0;
      // Position #9
      GcVec n9_pos = GcVec{0.0f, 0.0f, 0.0f}; float n9_x = 0; float n9_y = 0; float n9_z = 0; 
      n9_pos = gc_v3(X3, Y3, Z3); n9_x = X3; n9_y = Y3; n9_z = Z3;
      // Coords #10
      float n10_u = 0; float n10_v = 0; float n10_cx = 0; float n10_cy = 0; float n10_r = 0; float n10_angle = 0; 
      n10_u = u; n10_v = v; n10_cx = cx; n10_cy = cy; n10_r = r; n10_angle = ang;
      // Cube face #14
      float n14_face = 0; float n14_a = 0; float n14_b = 0; GcVec n14_normal = GcVec{0.0f, 0.0f, 0.0f}; float n14_nx = 0; float n14_ny = 0; float n14_nz = 0; 
      { const float ax_ = fabsf(X3), ay_ = fabsf(Y3), az_ = fabsf(Z3);
        float m_, pa_, pb_; n14_nx = 0.0f; n14_ny = 0.0f; n14_nz = 0.0f;
        if (cube && az_ >= ax_ && az_ >= ay_) { n14_face = Z3 >= 0 ? 4.0f : 5.0f; m_ = az_; pa_ = X3; pb_ = Y3; n14_nz = Z3 >= 0 ? 1.0f : -1.0f; }
        else if (cube && ay_ >= ax_)          { n14_face = Y3 >= 0 ? 2.0f : 3.0f; m_ = ay_; pa_ = X3; pb_ = Z3; n14_ny = Y3 >= 0 ? 1.0f : -1.0f; }
        else if (cube)                         { n14_face = X3 >= 0 ? 0.0f : 1.0f; m_ = ax_; pa_ = Y3; pb_ = Z3; n14_nx = X3 >= 0 ? 1.0f : -1.0f; }
        else                                   { n14_face = 4.0f; m_ = 1.0f; pa_ = X3; pb_ = Y3; n14_nz = 1.0f; }
        if (m_ < 1e-3f) m_ = 1e-3f;
        n14_a = pa_ / m_ * 0.5f + 0.5f; n14_b = pb_ / m_ * 0.5f + 0.5f; n14_normal = gc_v3(n14_nx, n14_ny, n14_nz); }
      // Vector #112
      GcVec n112_v = GcVec{0.0f, 0.0f, 0.0f}; 
      n112_v = gc_v3(n13_gx, n13_gy, n13_gz);
      // Vector #113
      GcVec n113_v = GcVec{0.0f, 0.0f, 0.0f}; 
      n113_v = gc_v3(n14_nx, n14_ny, n14_nz);
      // Dot 3 #15
      float n15_result = 0; 
      n15_result = gc_vdot(n112_v, n113_v);
      // Multiply #16
      float n16_result = 0; 
      n16_result = n15_result * n14_nx;
      // Subtract #17
      float n17_result = 0; 
      n17_result = n13_gx - n16_result;
      // Multiply #18
      float n18_result = 0; 
      n18_result = n15_result * n14_ny;
      // Subtract #19
      float n19_result = 0; 
      n19_result = n13_gy - n18_result;
      // Multiply #20
      float n20_result = 0; 
      n20_result = n15_result * n14_nz;
      // Subtract #21
      float n21_result = 0; 
      n21_result = n13_gz - n20_result;
      // Multiply #23
      float n23_result = 0; 
      n23_result = n17_result * n22_result;
      // Multiply #24
      float n24_result = 0; 
      n24_result = n23_result * 1.0f;
      // Add #25
      float n25_result = 0; 
      n25_result = n9_x + n24_result;
      // Multiply #26
      float n26_result = 0; 
      n26_result = n19_result * n22_result;
      // Multiply #27
      float n27_result = 0; 
      n27_result = n26_result * 1.0f;
      // Add #28
      float n28_result = 0; 
      n28_result = n9_y + n27_result;
      // Multiply #29
      float n29_result = 0; 
      n29_result = n21_result * n22_result;
      // Multiply #30
      float n30_result = 0; 
      n30_result = n29_result * 1.0f;
      // Add #31
      float n31_result = 0; 
      n31_result = n9_z + n30_result;
      // Vector #114
      GcVec n114_v = GcVec{0.0f, 0.0f, 0.0f}; 
      n114_v = gc_v3(n25_result, n28_result, n31_result);
      // Position to uv #32
      float n32_u = 0; float n32_v = 0; 
      gc_pos_uv(n114_v.x, n114_v.y, n114_v.z, W, H, B, cube, n32_u, n32_v);
      // Multiply #33
      float n33_result = 0; 
      n33_result = n17_result * n22_result;
      // Multiply #34
      float n34_result = 0; 
      n34_result = n33_result * -1.0f;
      // Add #35
      float n35_result = 0; 
      n35_result = n9_x + n34_result;
      // Multiply #36
      float n36_result = 0; 
      n36_result = n19_result * n22_result;
      // Multiply #37
      float n37_result = 0; 
      n37_result = n36_result * -1.0f;
      // Add #38
      float n38_result = 0; 
      n38_result = n9_y + n37_result;
      // Multiply #39
      float n39_result = 0; 
      n39_result = n21_result * n22_result;
      // Multiply #40
      float n40_result = 0; 
      n40_result = n39_result * -1.0f;
      // Add #41
      float n41_result = 0; 
      n41_result = n9_z + n40_result;
      // Vector #115
      GcVec n115_v = GcVec{0.0f, 0.0f, 0.0f}; 
      n115_v = gc_v3(n35_result, n38_result, n41_result);
      // Position to uv #42
      float n42_u = 0; float n42_v = 0; 
      gc_pos_uv(n115_v.x, n115_v.y, n115_v.z, W, H, B, cube, n42_u, n42_v);
      // Multiply #43
      float n43_result = 0; 
      n43_result = n17_result * n22_result;
      // Multiply #44
      float n44_result = 0; 
      n44_result = n43_result * 1.0f;
      // Add #45
      float n45_result = 0; 
      n45_result = n35_result + n44_result;
      // Multiply #46
      float n46_result = 0; 
      n46_result = n19_result * n22_result;
      // Multiply #47
      float n47_result = 0; 
      n47_result = n46_result * 1.0f;
      // Add #48
      float n48_result = 0; 
      n48_result = n38_result + n47_result;
      // Multiply #49
      float n49_result = 0; 
      n49_result = n21_result * n22_result;
      // Multiply #50
      float n50_result = 0; 
      n50_result = n49_result * 1.0f;
      // Add #51
      float n51_result = 0; 
      n51_result = n41_result + n50_result;
      // Vector #116
      GcVec n116_v = GcVec{0.0f, 0.0f, 0.0f}; 
      n116_v = gc_v3(n45_result, n48_result, n51_result);
      // Position to uv #52
      float n52_u = 0; float n52_v = 0; 
      gc_pos_uv(n116_v.x, n116_v.y, n116_v.z, W, H, B, cube, n52_u, n52_v);
      // Multiply #53
      float n53_result = 0; 
      n53_result = n17_result * n22_result;
      // Multiply #54
      float n54_result = 0; 
      n54_result = n53_result * -1.0f;
      // Add #55
      float n55_result = 0; 
      n55_result = n25_result + n54_result;
      // Multiply #56
      float n56_result = 0; 
      n56_result = n19_result * n22_result;
      // Multiply #57
      float n57_result = 0; 
      n57_result = n56_result * -1.0f;
      // Add #58
      float n58_result = 0; 
      n58_result = n28_result + n57_result;
      // Multiply #59
      float n59_result = 0; 
      n59_result = n21_result * n22_result;
      // Multiply #60
      float n60_result = 0; 
      n60_result = n59_result * -1.0f;
      // Add #61
      float n61_result = 0; 
      n61_result = n31_result + n60_result;
      // Vector #117
      GcVec n117_v = GcVec{0.0f, 0.0f, 0.0f}; 
      n117_v = gc_v3(n55_result, n58_result, n61_result);
      // Position to uv #62
      float n62_u = 0; float n62_v = 0; 
      gc_pos_uv(n117_v.x, n117_v.y, n117_v.z, W, H, B, cube, n62_u, n62_v);
      // Subtract #63
      float n63_result = 0; 
      n63_result = n52_u - n10_u;
      // Subtract #64
      float n64_result = 0; 
      n64_result = n52_v - n10_v;
      // Vector #118
      GcVec n118_v = GcVec{0.0f, 0.0f, 0.0f}; 
      n118_v = gc_v3(n63_result, n64_result, 0.0f);
      // Length #65
      float n65_result = 0; 
      n65_result = gc_vlen(n118_v);
      // Threshold #66
      bool n66_on = false; float n66_value = 0; 
      n66_on = n65_result >= 0.006f; n66_value = n66_on ? 1.0f : 0.0f;
      // Not #67
      bool n67_result = false; 
      n67_result = !n66_on;
      // Subtract #68
      float n68_result = 0; 
      n68_result = n62_u - n10_u;
      // Subtract #69
      float n69_result = 0; 
      n69_result = n62_v - n10_v;
      // Vector #119
      GcVec n119_v = GcVec{0.0f, 0.0f, 0.0f}; 
      n119_v = gc_v3(n68_result, n69_result, 0.0f);
      // Length #70
      float n70_result = 0; 
      n70_result = gc_vlen(n119_v);
      // Threshold #71
      bool n71_on = false; float n71_value = 0; 
      n71_on = n70_result >= 0.006f; n71_value = n71_on ? 1.0f : 0.0f;
      // Not #72
      bool n72_result = false; 
      n72_result = !n71_on;
      // Field #73
      float n73_value = 0; 
      { const int x_ = (int)floorf(gc_sat(n10_u) * (float)(W - 1) + 0.5f), y_ = (int)floorf(gc_sat(n10_v) * (float)(H - 1) + 0.5f);
        n73_value = gc_fr0[y_ * W + x_]; }
      // Field #74
      float n74_value = 0; 
      { const int x_ = (int)floorf(gc_sat(n32_u) * (float)(W - 1) + 0.5f), y_ = (int)floorf(gc_sat(n32_v) * (float)(H - 1) + 0.5f);
        n74_value = gc_fr0[y_ * W + x_]; }
      // Field #75
      float n75_value = 0; 
      { const int x_ = (int)floorf(gc_sat(n42_u) * (float)(W - 1) + 0.5f), y_ = (int)floorf(gc_sat(n42_v) * (float)(H - 1) + 0.5f);
        n75_value = gc_fr0[y_ * W + x_]; }
      // Threshold #76
      bool n76_on = false; float n76_value = 0; 
      n76_on = n31_result >= -0.999f; n76_value = n76_on ? 1.0f : 0.0f;
      // Not #77
      bool n77_result = false; 
      n77_result = !n76_on;
      // Threshold #78
      bool n78_on = false; float n78_value = 0; 
      n78_on = n74_value >= 0.5f; n78_value = n78_on ? 1.0f : 0.0f;
      // Max #79
      float n79_result = 0; 
      n79_result = (n78_value > (n77_result ? 1.0f : 0.0f)) ? n78_value : (n77_result ? 1.0f : 0.0f);
      // Threshold #80
      bool n80_on = false; float n80_value = 0; 
      n80_on = n73_value >= 0.5f; n80_value = n80_on ? 1.0f : 0.0f;
      // Subtract #82
      float n82_result = 0; 
      n82_result = 1.0f - n79_result;
      // Multiply #81
      float n81_result = 0; 
      n81_result = (n72_result ? 1.0f : 0.0f) * n82_result;
      // Subtract #83
      float n83_result = 0; 
      n83_result = 1.0f - n81_result;
      // Multiply #84
      float n84_result = 0; 
      n84_result = n80_value * n83_result;
      // Hash #85
      float n85_value = 0; 
      n85_value = gc_hash(n10_v, n10_u, n7_t);
      // Threshold #86
      bool n86_on = false; float n86_value = 0; 
      n86_on = n85_value >= 0.06f; n86_value = n86_on ? 1.0f : 0.0f;
      // Select #87
      float n87_result = 0; 
      n87_result = n77_result ? n86_value : 1.0f;
      // Multiply #88
      float n88_result = 0; 
      n88_result = n84_result * n87_result;
      // Threshold #89
      bool n89_on = false; float n89_value = 0; 
      n89_on = n75_value >= 0.5f; n89_value = n89_on ? 1.0f : 0.0f;
      // Not #90
      bool n90_result = false; 
      n90_result = !n80_on;
      // Multiply #91
      float n91_result = 0; 
      n91_result = n89_value * (n90_result ? 1.0f : 0.0f);
      // Multiply #92
      float n92_result = 0; 
      n92_result = n91_result * (n67_result ? 1.0f : 0.0f);
      // Cube ring #97
      float n97_around = 0; float n97_depth = 0; 
      { if (cube) {
          n97_around = cfx_atan2f(Y3, X3) * (0.5f / 3.14159265f) + 0.5f;
          n97_depth = (Z3 > 0.999f) ? (fmaxf(fabsf(X3), fabsf(Y3)) * 0.5f) : (0.5f + (1.0f - Z3) * 0.25f);
        } else { n97_around = u; n97_depth = v; } }
      // Threshold #98
      bool n98_on = false; float n98_value = 0; 
      n98_on = n97_depth >= 0.22f; n98_value = n98_on ? 1.0f : 0.0f;
      // Not #99
      bool n99_result = false; 
      n99_result = !n98_on;
      // Hash #100
      float n100_value = 0; 
      n100_value = gc_hash(n10_u, n10_v, n7_t);
      // Threshold #101
      bool n101_on = false; float n101_value = 0; 
      n101_on = n96_result >= n100_value; n101_value = n101_on ? 1.0f : 0.0f;
      // Multiply #102
      float n102_result = 0; 
      n102_result = n101_value * (n99_result ? 1.0f : 0.0f);
      // Max #103
      float n103_result = 0; 
      n103_result = (n88_result > n92_result) ? n88_result : n92_result;
      // Max #104
      float n104_result = 0; 
      n104_result = (n103_result > n102_result) ? n103_result : n102_result;
      // Field write #105
      
      gc_fw0[py * W + px] = n104_result;
      // Vector #120
      GcVec n120_v = GcVec{0.0f, 0.0f, 0.0f}; 
      n120_v = gc_v3(n9_x, n9_y, n9_z);
      // Vector #121
      GcVec n121_v = GcVec{0.0f, 0.0f, 0.0f}; 
      n121_v = gc_v3(n13_gx, n13_gy, n13_gz);
      // Dot 3 #106
      float n106_result = 0; 
      n106_result = gc_vdot(n120_v, n121_v);
      // Remap #107
      float n107_result = 0; 
      n107_result = 0.15f + (n106_result - -1.0f) * ((0.8f - 0.15f) / ((1.0f - -1.0f) != 0.0f ? (1.0f - -1.0f) : 1.0f));
      // Multiply #109
      float n109_result = 0; 
      n109_result = n104_result * n108_result;
      // Palette #110
      uint32_t n110_color = 0; 
      n110_color = mq_scale(SEGMENT.color_from_palette((uint8_t)(int)(n107_result * 255.0f), false, true, 0), (uint8_t)(gc_sat(n109_result) * 255.0f));
      // Output #111
      
      gc_out = n110_color;

      if (is2d) SEGMENT.setPixelColorXY(px, py, gc_out); else SEGMENT.setPixelColor(px, gc_out);
    }
  }
  FX_DONE;
}

static const char _data_FX_MODE_GYRO_SAND[] PROGMEM = "Gyro Sand@Pour rate,Glow,Tilt X,Tilt Y,,Beat bursts,,;;!;12v;sx=120,ix=150,c1=200,c2=190,o1=1,pal=8";
static CfxBankReg gyro_sand_reg(&mode_gyro_sand, _data_FX_MODE_GYRO_SAND);
