#include "wled.h"
#include "cube_fx_common.h"
#include "cube_fx_bank.h"

// ===========================================================================
// Ring Rain - generated by the WLED Effect Studio node editor
// ===========================================================================
// An ordinary effect: drop it into a usermod folder that has cube_fx_common.h
// and cube_fx_bank.h beside it and it compiles into the firmware unchanged.
// Edit the graph and regenerate, or edit this file by hand from here on.
// ===========================================================================

static inline float gc_sat(float x) { return x < 0.0f ? 0.0f : (x > 1.0f ? 1.0f : x); }
static inline float gc_fract(float x) { return x - floorf(x); }
// A vector: three floats on one wire.
struct GcVec { float x, y, z; };
static inline GcVec gc_v3(float x, float y, float z) { GcVec v; v.x = x; v.y = y; v.z = z; return v; }
static inline GcVec gc_vadd(GcVec a, GcVec b) { return gc_v3(a.x + b.x, a.y + b.y, a.z + b.z); }
static inline GcVec gc_vsub(GcVec a, GcVec b) { return gc_v3(a.x - b.x, a.y - b.y, a.z - b.z); }
static inline GcVec gc_vmul(GcVec a, GcVec b) { return gc_v3(a.x * b.x, a.y * b.y, a.z * b.z); }
static inline GcVec gc_vscale(GcVec a, float s) { return gc_v3(a.x * s, a.y * s, a.z * s); }
static inline float gc_vdot(GcVec a, GcVec b) { return a.x * b.x + a.y * b.y + a.z * b.z; }
static inline float gc_vlen(GcVec a) { return sqrtf(gc_vdot(a, a)); }
static inline GcVec gc_vnorm(GcVec a) { const float L = gc_vlen(a); return L > 1e-6f ? gc_vscale(a, 1.0f / L) : gc_v3(0.0f, 0.0f, 1.0f); }
static inline GcVec gc_vcross(GcVec a, GcVec b) { return gc_v3(a.y * b.z - a.z * b.y, a.z * b.x - a.x * b.z, a.x * b.y - a.y * b.x); }
static inline GcVec gc_col2v(uint32_t c) { return gc_v3(((c >> 16) & 255) * (1.0f / 255.0f), ((c >> 8) & 255) * (1.0f / 255.0f), (c & 255) * (1.0f / 255.0f)); }
static inline uint32_t gc_v2col(GcVec v) { return RGBW32((uint8_t)(gc_sat(v.x) * 255.0f), (uint8_t)(gc_sat(v.y) * 255.0f), (uint8_t)(gc_sat(v.z) * 255.0f), 0); }
// Rotate v about a unit axis by an angle (Rodrigues).
static inline GcVec gc_vrot(GcVec v, GcVec axis, float rad) {
  const GcVec k = gc_vnorm(axis); const float c = cosf(rad), s = sinf(rad);
  return gc_vadd(gc_vadd(gc_vscale(v, c), gc_vscale(gc_vcross(k, v), s)), gc_vscale(k, gc_vdot(k, v) * (1.0f - c)));
}
static inline float gc_rnd() { return (float)hw_random16() * (1.0f / 65535.0f); }
// A stable 0..1 from a position and a seed - the same every frame for the same
// inputs, so cells, tiles and columns can each own a random number.
static inline float gc_hash(float x, float y, float seed) {
  uint32_t h = (uint32_t)(int32_t)floorf(x * 4096.0f) * 374761393u
             ^ (uint32_t)(int32_t)floorf(y * 4096.0f) * 668265263u
             ^ (uint32_t)(int32_t)floorf(seed * 4096.0f) * 2246822519u;
  h ^= h >> 13; h *= 1274126177u; h ^= h >> 16;
  return (float)(h & 0xFFFFFFu) * (1.0f / 16777215.0f);
}
// Last frame's colour at a logical position (0..1, 0..1). On a matrix that is
// a neighbour read for trails and flows; the pixels already written this
// frame read as this frame's, as WLED's own fire effects accept.
// The inverse of the lid-and-walls ruler: (around, depth) back to the logical
// pixel, as u, v - the exact inverse of cfx_pos, so a read there lands on the
// pixel Cube ring would call that. Lets a feedback read step along the ring.
static inline int gc_q(float t, int B) { int i = (int)floorf((t + 1.0f) * 0.5f * (float)B); return i < 0 ? 0 : (i > B - 1 ? B - 1 : i); }
static inline void gc_ring_uv(float around, float depth, int W, int H, int B, bool cube, float &u, float &v) {
  around -= floorf(around);
  if (!cube) { u = around; v = gc_sat(depth); return; }
  const float a = (around - 0.5f) * 6.2831853f;
  float cx_ = cosf(a), sy_ = sinf(a);
  const float m = fmaxf(fabsf(cx_), fabsf(sy_)); if (m > 1e-6f) { cx_ /= m; sy_ /= m; }
  int px_, py_;
  if (depth < 0.5f) { const float r = depth * 2.0f; px_ = B + gc_q(cx_ * r, B); py_ = B + gc_q(-sy_ * r, B); }
  else {
    const float Z = 1.0f - (depth - 0.5f) * 4.0f;
    if (fabsf(sy_) >= fabsf(cx_)) { px_ = B + gc_q(cx_, B); py_ = (sy_ > 0) ? gc_q(Z, B) : 2 * B + gc_q(-Z, B); }
    else                          { py_ = B + gc_q(-sy_, B); px_ = (cx_ < 0) ? gc_q(Z, B) : 2 * B + gc_q(-Z, B); }
  }
  u = (W > 1) ? (float)px_ / (float)(W - 1) : 0.5f; v = (H > 1) ? (float)py_ / (float)(H - 1) : 0.5f;
}
// A finite reflection group's mirrors, each normal pointed at one generic
// direction so every set is the positive roots of a single chamber and the
// fold terminates (see cube_fx_39_kaleidoscope.cpp for the reasoning).
//   sym 0..7  dihedral D(n), n = sym + 3 (with the equator)
//   sym 8     tetrahedral   sym 9  octahedral   sym 10  icosahedral
static int gc_mirrors(int sym, float m[16][3]) {
  int n = 0;
  const float gx = 0.2374f, gy = 0.4451f, gz = 0.8632f;
  #define GC_MIR(a, b, c) { if (n < 16) { m[n][0] = (a); m[n][1] = (b); m[n][2] = (c); n++; } }
  if (sym <= 7) {
    const int k = sym + 3;
    for (int i = 0; i < k; i++) { const float a = (float)i * 3.14159265f / (float)k; GC_MIR(-sinf(a), cosf(a), 0.0f); }
    GC_MIR(0.0f, 0.0f, 1.0f);
  } else if (sym <= 9) {
    if (sym == 9) { GC_MIR(1, 0, 0); GC_MIR(0, 1, 0); GC_MIR(0, 0, 1); }
    GC_MIR(1, -1, 0); GC_MIR(1, 1, 0); GC_MIR(0, 1, -1); GC_MIR(0, 1, 1); GC_MIR(1, 0, -1); GC_MIR(1, 0, 1);
  } else {
    const float P = 1.61803399f, Q = 0.61803399f;
    GC_MIR(1, 0, 0); GC_MIR(0, 1, 0); GC_MIR(0, 0, 1);
    for (int a = 0; a < 2; a++) for (int b = 0; b < 2; b++) {
      const float sa = a ? -1.0f : 1.0f, sb = b ? -1.0f : 1.0f;
      GC_MIR(1.0f, sa * P, sb * Q); GC_MIR(sa * P, sb * Q, 1.0f); GC_MIR(sb * Q, 1.0f, sa * P);
    }
  }
  #undef GC_MIR
  for (int j = 0; j < n; j++) {
    const float L = sqrtf(m[j][0] * m[j][0] + m[j][1] * m[j][1] + m[j][2] * m[j][2]);
    float sgn = (m[j][0] * gx + m[j][1] * gy + m[j][2] * gz) < 0.0f ? -1.0f : 1.0f;
    if (L > 0.0f) sgn /= L;
    m[j][0] *= sgn; m[j][1] *= sgn; m[j][2] *= sgn;
  }
  return n;
}
// Reflect a direction into the group's fundamental domain: bounce off any
// mirror it is behind until nothing moves. Two or three sweeps in practice.
static inline void gc_fold(int sym, float &x, float &y, float &z) {
  static float mir[16][3]; static int nm = 0, have = -1;
  if (have != sym) { nm = gc_mirrors(sym, mir); have = sym; }
  for (int pass = 0; pass < 4; pass++) {
    bool moved = false;
    for (int j = 0; j < nm; j++) {
      const float d = x * mir[j][0] + y * mir[j][1] + z * mir[j][2];
      if (d < 0.0f) { const float t = 2.0f * d; x -= t * mir[j][0]; y -= t * mir[j][1]; z -= t * mir[j][2]; moved = true; }
    }
    if (!moved) break;
  }
}
// Escape time of z -> z^2 + c, smoothed, as 0..1 (1 = never escaped); a
// Julia set when jx, jy are given instead of the point itself.
static inline float gc_mandel(float cx, float cy, float zx, float zy, int maxit) {
  int i = 0; float x2 = zx * zx, y2 = zy * zy;
  while (i < maxit && x2 + y2 < 16.0f) { zy = 2.0f * zx * zy + cy; zx = x2 - y2 + cx; x2 = zx * zx; y2 = zy * zy; i++; }
  if (i >= maxit) return 1.0f;
  const float nu = (float)i + 1.0f - logf(logf(sqrtf(x2 + y2)) / 0.6931472f) / 0.6931472f;
  return gc_sat(nu / (float)maxit);
}
// Any point in the -1..1 box back to the logical pixel that shows it: the
// point is pushed onto the cube's surface (the box's own max-norm) and the
// face mapping of cfx_pos is run backwards. A read one step along gravity,
// or along any 3-D direction, is this and then Field or Previous at.
static inline void gc_pos_uv(float X, float Y, float Z, int W, int H, int B, bool cube, float &u, float &v) {
  if (!cube) { u = gc_sat((X + 1.0f) * 0.5f); v = gc_sat((1.0f - Y) * 0.5f); return; }
  const float m = fmaxf(fabsf(X), fmaxf(fabsf(Y), fabsf(Z)));
  if (m > 1e-6f) { X /= m; Y /= m; Z /= m; }
  int px_, py_;
  const float ax = fabsf(X), ay = fabsf(Y), az = fabsf(Z);
  if (az >= ax && az >= ay) {                                   // top (or the missing bottom)
    px_ = B + gc_q(X, B); py_ = B + gc_q(-Y, B);
  } else if (ay >= ax) {
    px_ = B + gc_q(X, B); py_ = (Y > 0) ? gc_q(Z, B) : 2 * B + gc_q(-Z, B);
  } else {
    py_ = B + gc_q(-Y, B); px_ = (X < 0) ? gc_q(Z, B) : 2 * B + gc_q(-Z, B);
  }
  u = (W > 1) ? (float)px_ / (float)(W - 1) : 0.5f; v = (H > 1) ? (float)py_ / (float)(H - 1) : 0.5f;
}
// A (P, Q) torus knot seen from the centre: does the ray along direction n
// hit the knot's tube, and where. For azimuth u the knot passes P times, at
// t = (u + 2 pi k) / P; each pass is a point in the half-plane of u, and the
// ray hits its tube if it passes within `tube` of it. The nearest hit wins.
static inline bool gc_knot(float nx, float ny, float nz, int P, int Q, float R, float r, float tube,
                           float &along, float &edge, float &Nx, float &Ny, float &Nz) {
  const float sxy = sqrtf(nx * nx + ny * ny);
  const float u = cfx_atan2f(ny, nx);
  float bestL = 1e9f, bestT = 0.0f, bestRho = 0.0f, bestZ = 0.0f, bestD2 = 0.0f;
  const float tube2 = tube * tube;
  for (int k = 0; k < P; k++) {
    const float t = (u + 6.2831853f * (float)k) / (float)P;
    const float v = (float)Q * t;
    const float rho = R + r * cosf(v), zz = r * sinf(v);
    const float ell = rho * sxy + zz * nz;
    if (ell <= 0.0f) continue;
    float d2 = rho * rho + zz * zz - ell * ell; if (d2 < 0.0f) d2 = 0.0f;
    if (d2 < tube2) {
      const float hit = ell - sqrtf(tube2 - d2);
      if (hit > 0.0f && hit < bestL) { bestL = hit; bestT = t; bestRho = rho; bestZ = zz; bestD2 = d2; }
    }
  }
  if (bestL > 1e8f) { along = 0.0f; edge = 1.0f; Nx = Ny = 0.0f; Nz = 1.0f; return false; }
  const float qx = bestL * nx, qy = bestL * ny, qz = bestL * nz;
  const float cu = (sxy > 1e-6f) ? (nx / sxy) : 1.0f, su = (sxy > 1e-6f) ? (ny / sxy) : 0.0f;
  Nx = qx - bestRho * cu; Ny = qy - bestRho * su; Nz = qz - bestZ;
  const float NL = sqrtf(Nx * Nx + Ny * Ny + Nz * Nz); const float iN = (NL > 1e-6f) ? 1.0f / NL : 1.0f;
  Nx *= iN; Ny *= iN; Nz *= iN;
  along = bestT * (1.0f / 6.2831853f); along -= floorf(along);
  edge = sqrtf(bestD2) / tube;
  return true;
}
#if __has_include("cube_fx_imu.h")
  #include "cube_fx_imu.h"
  #define GC_HAS_IMU 1
#endif
// Gray-Scott reaction-diffusion on a small grid, periodic in x (a tunnel's
// azimuth), clamped in y. U and V interleaved; one Euler step per call.
static inline void gc_gray_scott(float *G, int gw, int gh, float Du, float Dv, float F, float k, float *tmp) {
  for (int y = 0; y < gh; y++) for (int x = 0; x < gw; x++) {
    const int i = (y * gw + x) * 2;
    const int xl = (x + gw - 1) % gw, xr = (x + 1) % gw, yu = y > 0 ? y - 1 : y, yd = y < gh - 1 ? y + 1 : y;
    const float u = G[i], v = G[i + 1];
    const float lu = G[(y * gw + xl) * 2] + G[(y * gw + xr) * 2] + G[(yu * gw + x) * 2] + G[(yd * gw + x) * 2] - 4.0f * u;
    const float lv = G[(y * gw + xl) * 2 + 1] + G[(y * gw + xr) * 2 + 1] + G[(yu * gw + x) * 2 + 1] + G[(yd * gw + x) * 2 + 1] - 4.0f * v;
    const float uvv = u * v * v;
    tmp[i]     = u + Du * lu - uvv + F * (1.0f - u);
    tmp[i + 1] = v + Dv * lv + uvv - (F + k) * v;
  }
  for (int i = 0; i < gw * gh * 2; i++) G[i] = tmp[i] < 0.0f ? 0.0f : (tmp[i] > 1.0f ? 1.0f : tmp[i]);
}
// One row of a text bitmap: rows separated by '/', '.' transparent, a digit
// its colour slot. Returns the slot at (u, v) or -1.
static inline int gc_bitmap(const char *bm, float u, float v) {
  int rows = 1; for (const char *p = bm; *p; p++) if (*p == '/') rows++;
  int r = (int)floorf(gc_sat(v) * (float)rows); if (r >= rows) r = rows - 1;
  const char *p = bm; for (int i = 0; i < r; i++) { while (*p && *p != '/') p++; if (*p) p++; }
  int cols = 0; for (const char *q = p; *q && *q != '/'; q++) cols++;
  if (cols == 0) return -1;
  int c = (int)floorf(gc_sat(u) * (float)cols); if (c >= cols) c = cols - 1;
  const char ch = p[c];
  return (ch >= '0' && ch <= '9') ? (ch - '0') : -1;
}
static inline uint32_t gc_prev_at(float u, float v, int W, int H, bool is2d) {
  int x = (int)floorf(gc_sat(u) * (float)(W - 1) + 0.5f), y = (int)floorf(gc_sat(v) * (float)(H - 1) + 0.5f);
  return is2d ? SEGMENT.getPixelColorXY(x, y) : SEGMENT.getPixelColor(x);
}
// The palette-source colour lives in the cube_fx palettes usermod. Weak, so a
// build without that usermod still links and the node falls back to the
// segment's own palette.
uint32_t cfxPaletteSourceColor(uint8_t pos, uint8_t bri) __attribute__((weak));
static inline uint32_t gc_srcpal(uint8_t pos, uint8_t bri) {
  if (cfxPaletteSourceColor) return cfxPaletteSourceColor(pos, bri);
  return mq_scale(SEGMENT.color_from_palette(pos, false, true, 0), bri);
}
static inline uint32_t gc_hsv(float h, float s, float v) {
  h -= floorf(h); const float hh = h * 6.0f; const int i = (int)hh; const float f = hh - i;
  const float p = v * (1.0f - s), q = v * (1.0f - s * f), t = v * (1.0f - s * (1.0f - f));
  float r, g, b;
  switch (i) { case 0: r=v;g=t;b=p; break; case 1: r=q;g=v;b=p; break; case 2: r=p;g=v;b=t; break;
               case 3: r=p;g=q;b=v; break; case 4: r=t;g=p;b=v; break; default: r=v;g=p;b=q; break; }
  return RGBW32((uint8_t)(gc_sat(r)*255.0f), (uint8_t)(gc_sat(g)*255.0f), (uint8_t)(gc_sat(b)*255.0f), 0);
}
static inline uint32_t gc_blend_over(uint32_t u, uint32_t o, float a)     { return color_blend(u, o, (uint8_t)(a * 255.0f)); }
static inline uint32_t gc_blend_add(uint32_t u, uint32_t o, float a)      { return color_add(u, mq_scale(o, (uint8_t)(a * 255.0f)), true); }
static inline uint32_t gc_blend_max(uint32_t u, uint32_t o, float a) {
  o = mq_scale(o, (uint8_t)(a * 255.0f)); uint32_t r = 0;
  for (int s = 0; s < 24; s += 8) { const uint32_t x = (u >> s) & 255, y = (o >> s) & 255; r |= (x > y ? x : y) << s; }
  return r; }
static inline uint32_t gc_blend_min(uint32_t u, uint32_t o, float a) {
  uint32_t r = 0;
  for (int s = 0; s < 24; s += 8) { const uint32_t x = (u >> s) & 255, y = (o >> s) & 255; const uint32_t m = x < y ? x : y;
    r |= (uint32_t)(x + (int)((int)m - (int)x) * a) << s; }
  return r; }
static inline uint32_t gc_blend_multiply(uint32_t u, uint32_t o, float a) {
  uint32_t r = 0;
  for (int s = 0; s < 24; s += 8) { const uint32_t x = (u >> s) & 255, y = (o >> s) & 255; const uint32_t m = (x * y) / 255u;
    r |= (uint32_t)(x + (int)((int)m - (int)x) * a) << s; }
  return r; }
static inline uint32_t gc_blend_screen(uint32_t u, uint32_t o, float a) {
  uint32_t r = 0;
  for (int s = 0; s < 24; s += 8) { const uint32_t x = (u >> s) & 255, y = (o >> s) & 255; const uint32_t m = 255u - ((255u - x) * (255u - y)) / 255u;
    r |= (uint32_t)(x + (int)((int)m - (int)x) * a) << s; }
  return r; }

static FX_RET mode_ring_rain() {
  if (!strip.isMatrix && !SEGMENT.is2D() && SEGLEN < 1) { FX_DONE; }
  const bool is2d = SEGMENT.is2D();
  const int W = is2d ? SEG_W : SEGLEN, H = is2d ? SEG_H : 1;
  const int N = W * H;
  const bool cube = is2d && cfx_isCube(W, H);
  const int  B    = cube ? (W / 3) : 1;
  static uint8_t clk_[2] = {0, 0};
  const uint16_t dt = fx_dt8(clk_);
  const float t = (float)strip.now * 0.001f;
  (void)N; (void)dt; (void)t;
  // --- state kept between frames: 1 floats, 0 field(s) of N ------
  const bool gc_first = (SEGENV.call == 0);
  float *gc_st = nullptr;
  if (SEGENV.allocateData((1 + 2 * 0 * N) * sizeof(float))) gc_st = (float *)SEGENV.data;
  static float gc_st_fallback[1]; if (!gc_st) gc_st = gc_st_fallback;
  (void)gc_first;

  // --- frame scope -----------------------------------------------------------
      // Speed #1
      float n1_value = 0; 
      n1_value = SEGMENT.speed * (1.0f / 255.0f);
      // Intensity #2
      float n2_value = 0; 
      n2_value = SEGMENT.intensity * (1.0f / 255.0f);
      // Custom 1 #3
      float n3_value = 0; 
      n3_value = SEGMENT.custom1 * (1.0f / 255.0f);
      // Check 1 #4
      bool n4_on = false; 
      n4_on = SEGMENT.check1;
      // Audio #5
      float n5_volume = 0; float n5_bass = 0; float n5_mid = 0; float n5_treble = 0; bool n5_beat = false; float n5_hit = 0; 
      { um_data_t *um = cfx_getAudioData();
        int b_, m_, t_; cfx_bands((const uint8_t *)um->u_data[2], b_, m_, t_);
        n5_volume = *(float *)um->u_data[0] * (1.0f / 255.0f);
        n5_bass = b_ * (1.0f / 255.0f); n5_mid = m_ * (1.0f / 255.0f); n5_treble = t_ * (1.0f / 255.0f);
        const uint8_t k_ = fx_lowBeat(um);
        n5_beat = k_ != 0; n5_hit = k_ * (1.0f / 255.0f); }
      // Remap #8
      float n8_result = 0; 
      n8_result = 8.0f + (n3_value - 0.0f) * ((64.0f - 8.0f) / ((1.0f - 0.0f) != 0.0f ? (1.0f - 0.0f) : 1.0f));
      // Remap #13
      float n13_result = 0; 
      n13_result = 0.1f + (n1_value - 0.0f) * ((1.5f - 0.1f) / ((1.0f - 0.0f) != 0.0f ? (1.0f - 0.0f) : 1.0f));
      // Integrate #16
      float n16_value = 0; 
      if (gc_first || false) gc_st[0] = 0.0f;
      gc_st[0] += 1.0f * ((float)dt * 0.001f);
      if (0.0f > 0.0f) gc_st[0] -= floorf(gc_st[0] / 0.0f) * 0.0f;
      n16_value = gc_st[0];
      // Remap #23
      float n23_result = 0; 
      n23_result = 14.0f + (n2_value - 0.0f) * ((3.0f - 14.0f) / ((1.0f - 0.0f) != 0.0f ? (1.0f - 0.0f) : 1.0f));
      // Multiply #27
      float n27_result = 0; 
      n27_result = n5_bass * 1.5f;
      // Select #28
      float n28_result = 0; 
      n28_result = n4_on ? n27_result : 0.0f;
      // Add #29
      float n29_result = 0; 
      n29_result = 0.6f + n28_result;
      // Colour #33
      uint32_t n33_color = 0; 
      n33_color = RGBW32(255, 255, 255, 0);

  // --- per pixel ---------------------------------------------------------------
  const int cols = W, rows = H; (void)rows;          // the net-skip macros' names
  CFX_NET_PREP();
  for (int py = 0; py < H; py++) {
    CFX_NET_ROW(py);
    for (int px = 0; px < W; px++) {
      CFX_NET_SKIP(px);
      const float u = (W > 1) ? (float)px / (float)(W - 1) : 0.5f;
      const float v = (H > 1) ? (float)py / (float)(H - 1) : 0.5f;
      const float cx = u * 2.0f - 1.0f, cy = 1.0f - v * 2.0f;
      const float r = sqrtf(cx * cx + cy * cy);
      const float ang = cfx_atan2f(cy, cx);
      float nx, ny, nz, X3, Y3, Z3;                 // direction (unit) and position (-1..1 box)
      if (cube) {
        cfx_pos(px, py, W, H, B, true, X3, Y3, Z3);
        const float L = sqrtf(X3 * X3 + Y3 * Y3 + Z3 * Z3); const float iL = L > 1e-6f ? 1.0f / L : 1.0f;
        nx = X3 * iL; ny = Y3 * iL; nz = Z3 * iL;
      } else {
        X3 = cx; Y3 = cy; Z3 = 0.0f;
        const float Z = 1.0f - (cx * cx + cy * cy) * 0.5f;
        const float L = sqrtf(cx * cx + cy * cy + Z * Z); const float iL = L > 1e-6f ? 1.0f / L : 1.0f;
        nx = cx * iL; ny = cy * iL; nz = Z * iL;
      }
      (void)u; (void)v; (void)r; (void)ang; (void)nx; (void)ny; (void)nz; (void)X3; (void)Y3; (void)Z3;
      uint32_t gc_out = 0;
      // Cube ring #7
      float n7_around = 0; float n7_depth = 0; 
      { if (cube) {
          n7_around = cfx_atan2f(Y3, X3) * (0.5f / 3.14159265f) + 0.5f;
          n7_depth = (Z3 > 0.999f) ? (fmaxf(fabsf(X3), fabsf(Y3)) * 0.5f) : (0.5f + (1.0f - Z3) * 0.25f);
        } else { n7_around = u; n7_depth = v; } }
      // Multiply #9
      float n9_result = 0; 
      n9_result = n7_around * n8_result;
      // Floor #10
      float n10_result = 0; 
      n10_result = floorf(n9_result);
      // Hash #11
      float n11_value = 0; 
      n11_value = gc_hash(n10_result, 0.0f, 1.0f);
      // Hash #12
      float n12_value = 0; 
      n12_value = gc_hash(n10_result, 1.0f, 1.0f);
      // Remap #14
      float n14_result = 0; 
      n14_result = 0.3f + (n11_value - 0.0f) * ((1.0f - 0.3f) / ((1.0f - 0.0f) != 0.0f ? (1.0f - 0.0f) : 1.0f));
      // Multiply #15
      float n15_result = 0; 
      n15_result = n14_result * n13_result;
      // Multiply #17
      float n17_result = 0; 
      n17_result = n16_value * n15_result;
      // Add #18
      float n18_result = 0; 
      n18_result = n17_result + n12_value;
      // Fract #19
      float n19_result = 0; 
      n19_result = n18_result - floorf(n18_result);
      // Subtract #20
      float n20_result = 0; 
      n20_result = n19_result - n7_depth;
      // Modulo #21
      float n21_result = 0; 
      n21_result = (1.0f != 0.0f) ? n20_result - floorf(n20_result / 1.0f) * 1.0f : 0.0f;
      // Subtract #22
      float n22_result = 0; 
      n22_result = 1.0f - n21_result;
      // Power #24
      float n24_result = 0; 
      n24_result = powf(n22_result < 0.0f ? 0.0f : n22_result, n23_result);
      // Threshold #25
      bool n25_on = false; float n25_value = 0; 
      n25_on = n21_result >= 0.035f; n25_value = n25_on ? 1.0f : 0.0f;
      // Select #26
      float n26_result = 0; 
      n26_result = n25_on ? 0.0f : 1.0f;
      // Multiply #30
      float n30_result = 0; 
      n30_result = n24_result * n29_result;
      // Multiply #31
      float n31_result = 0; 
      n31_result = n11_value * 0.6f;
      // Palette #32
      uint32_t n32_color = 0; 
      n32_color = mq_scale(SEGMENT.color_from_palette((uint8_t)(int)(n31_result * 255.0f), false, true, 0), (uint8_t)(gc_sat(n30_result) * 255.0f));
      // Blend #34
      uint32_t n34_color = 0; 
      n34_color = gc_blend_over(n32_color, n33_color, gc_sat(n26_result));
      // Output #35
      
      gc_out = n34_color;

      if (is2d) SEGMENT.setPixelColorXY(px, py, gc_out); else SEGMENT.setPixelColor(px, gc_out);
    }
  }
  FX_DONE;
}

static const char _data_FX_MODE_RING_RAIN[] PROGMEM = "Ring Rain@Fall speed,Trail,Columns,,,Bass brightens,,;;!;12v;sx=128,ix=128,c1=128,o1=1,pal=10";
static CfxBankReg ring_rain_reg(&mode_ring_rain, _data_FX_MODE_RING_RAIN);
